services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logistics_db
    ports:
      - "5434:5432"
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    ports:
      - "6382:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # 🔥 KEY FIX (dual listeners)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui
    depends_on:
      - kafka
    ports:
      - "9999:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

  inventory-service:
    build:
      context: ./backend/inventory-service
    depends_on:
      - postgres
    ports:
      - "2502:2502"
    environment:
      SERVER_PORT: 2502
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/logistics_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      EUREKA_CLIENT_ENABLED: "false"

  order-service:
    build:
      context: ./backend/order-service
    depends_on:
      - postgres
      - kafka
      - inventory-service
    ports:
      - "2501:2501"
    environment:
      SERVER_PORT: 2501
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/scm_order_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      INVENTORY_SERVICE_URL: http://inventory-service:2502
      EUREKA_CLIENT_ENABLED: "false"

  prometheus:
    image: prom/prometheus:v2.54.1
    depends_on:
      - inventory-service
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
