server:
  port: ${SERVER_PORT:2501}

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5434/scm_order_db
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

inventory:
  service:
    url: ${INVENTORY_SERVICE_URL:http://localhost:2502}

eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:true}
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true